# Generated by Django 5.2.8 on 2025-11-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_verbose_name_to_ipdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineinstance',
            name='acquisition_notes',
            field=models.TextField(blank=True, help_text='Details about acquisition history', verbose_name='Acquisition Notes'),
        ),
        migrations.AlterField(
            model_name='machineinstance',
            name='name_override',
            field=models.CharField(blank=True, help_text='Override the model name for this specific instance', max_length=200, verbose_name='Name Override'),
        ),
        migrations.AlterField(
            model_name='machineinstance',
            name='operational_status',
            field=models.CharField(choices=[('good', 'Good'), ('unknown', 'Unknown'), ('fixing', 'Fixing'), ('broken', 'Broken')], default='unknown', help_text='Current working condition', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='machineinstance',
            name='ownership_credit',
            field=models.CharField(blank=True, help_text='Credit for ownership', max_length=300, verbose_name='Ownership Credit'),
        ),
        migrations.AlterField(
            model_name='machineinstance',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number from manufacturer', max_length=100, verbose_name='Serial Number'),
        ),
    ]
