# Generated by Django 5.2.8 on 2025-11-29 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name for this webhook endpoint.', max_length=100)),
                ('url', models.URLField(help_text='The webhook URL to send notifications to.', max_length=500)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this endpoint is active.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhooks_enabled', models.BooleanField(default=True, help_text='Master switch to enable/disable all webhook notifications.')),
                ('problem_reports_enabled', models.BooleanField(default=True, help_text='Enable webhooks for problem report events.')),
                ('log_entries_enabled', models.BooleanField(default=True, help_text='Enable webhooks for log entry events.')),
            ],
            options={
                'verbose_name': 'Webhook Settings',
                'verbose_name_plural': 'Webhook Settings',
            },
        ),
        migrations.CreateModel(
            name='WebhookEventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('problem_report_created', 'Problem Report Created'), ('problem_report_closed', 'Problem Report Closed'), ('problem_report_reopened', 'Problem Report Reopened'), ('log_entry_created', 'Log Entry Created')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this event subscription is active.')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='webhooks.webhookendpoint')),
            ],
            options={
                'ordering': ['event_type'],
                'unique_together': {('endpoint', 'event_type')},
            },
        ),
    ]
