# Generated by Django 5.2.8 on 2025-11-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookeventsubscription',
            name='event_type',
            field=models.CharField(choices=[('problem_report_created', 'Problem Report Created'), ('log_entry_created', 'Log Entry Created')], max_length=50),
        ),
    ]
