# Generated by Django 5.2.12 on 2026-05-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_maintainers_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintainer',
            options={'ordering': ['user__username'], 'permissions': [('can_access_maintainer_portal', 'Can access the maintainer portal'), ('can_manage_catalog', 'Can manage catalog (create machines, print QR codes)')]},
        ),
    ]
