# Generated by Django 5.2.14 on 2026-05-17 00:15

import django.db.models.deletion
import flipfix.apps.accounts.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_catalog_managers_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintainer',
            options={'ordering': ['user__username'], 'permissions': [('can_access_maintainer_portal', 'Can access the maintainer portal'), ('can_manage_catalog', 'Can manage catalog (create machines, print QR codes)'), ('can_view_user_profiles', 'Can view the user directory and profile pages')]},
        ),
        migrations.AddField(
            model_name='maintainer',
            name='bio',
            field=models.TextField(blank=True, help_text="Short markdown bio shown on the user's profile page.", max_length=300),
        ),
        migrations.CreateModel(
            name='HistoricalMaintainerMedia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=20)),
                ('transcode_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('display_order', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.TextField(max_length=100)),
                ('thumbnail_file', models.TextField(blank=True, max_length=100, null=True)),
                ('transcoded_file', models.TextField(blank=True, max_length=100, null=True)),
                ('poster_file', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('maintainer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.maintainer')),
            ],
            options={
                'verbose_name': 'historical Maintainer media',
                'verbose_name_plural': 'historical Maintainer media',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MaintainerMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=20)),
                ('transcode_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('display_order', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to=flipfix.apps.accounts.models.maintainer_media_upload_to)),
                ('thumbnail_file', models.FileField(blank=True, null=True, upload_to=flipfix.apps.accounts.models.maintainer_media_upload_to)),
                ('transcoded_file', models.FileField(blank=True, null=True, upload_to=flipfix.apps.accounts.models.maintainer_media_upload_to)),
                ('poster_file', models.ImageField(blank=True, null=True, upload_to=flipfix.apps.accounts.models.maintainer_media_upload_to)),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='accounts.maintainer')),
            ],
            options={
                'verbose_name': 'Maintainer media',
                'verbose_name_plural': 'Maintainer media',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
