# Generated by Django 5.2.14 on 2026-05-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_check_reserved_usernames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainer',
            name='bio',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
