# Generated by Django 5.2.14 on 2026-05-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_maintainer_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainer',
            name='last_active_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Most recent authenticated request from this maintainer. Updated at most once per day.', null=True),
        ),
    ]
