# Generated by Django 5.2.14 on 2026-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_maintainer_last_active_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainer',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
