# Generated by Django 5.2.16 on 2026-07-17 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0006_remove_unique_message_id_add_compound_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler_name', models.CharField(help_text="Webhook handler name, e.g. 'log_entry' (see webhook_handlers/).", max_length=50)),
                ('object_id', models.PositiveIntegerField(help_text='Primary key of the record to notify about.')),
                ('buffered_at', models.DateTimeField(auto_now_add=True, help_text='When the event was buffered (≈ when the record was created).')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When this event was flushed to Discord; null while pending.', null=True)),
                ('actor', models.ForeignKey(help_text='The user whose activity this event belongs to; the grouping key.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending notification',
                'verbose_name_plural': 'Pending notifications',
                'ordering': ['buffered_at'],
                'indexes': [models.Index(fields=['sent_at', 'actor', 'buffered_at'], name='discord_pen_sent_at_8ee598_idx')],
            },
        ),
    ]
