# Generated by Django 5.2.12 on 2026-03-14 15:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_historicalproblemreport_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallogentry',
            name='time_spent',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total person-hours spent (all people combined).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='logentry',
            name='time_spent',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total person-hours spent (all people combined).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
