# Generated by Django 5.2.12 on 2026-03-14 16:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_historicallogentry_time_spent_logentry_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallogentry',
            name='time_spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total person-hours spent (all people combined).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='time_spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total person-hours spent (all people combined).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
