# Generated by Django 5.2.15 on 2026-06-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_alter_historicallogentry_time_spent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g. 'Clean the playfield'.", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional guidance shown to maintainers.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which tasks appear.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tasks are hidden from forms and lists but keep their history.')),
            ],
            options={
                'verbose_name': 'Maintenance task type',
                'verbose_name_plural': 'Maintenance task types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='logentry',
            name='maintenance_tasks',
            field=models.ManyToManyField(blank=True, help_text='Recurring maintenance tasks completed in this entry.', related_name='log_entries', to='maintenance.maintenancetasktype'),
        ),
    ]
