# Generated by Django 5.2.15 on 2026-07-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_seed_maintenance_task_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallogentry',
            name='submission_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Idempotency token supplied by the client (web form render or API call). Collapses accidental resubmits from a slow or timed-out connection. NULL for entries created without a token.', null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='submission_id',
            field=models.UUIDField(blank=True, help_text='Idempotency token supplied by the client (web form render or API call). Collapses accidental resubmits from a slow or timed-out connection. NULL for entries created without a token.', null=True, unique=True),
        ),
    ]
