# Generated by Django 5.2.16 on 2026-08-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_reconcile_unplayable_machine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallogentry',
            name='announce',
            field=models.BooleanField(default=True, help_text='Post this to Discord when it is created. Turn off for routine paperwork such as a pasted checklist.'),
        ),
        migrations.AddField(
            model_name='historicalproblemreport',
            name='announce',
            field=models.BooleanField(default=True, help_text='Post this to Discord when it is created. Turn off for routine paperwork such as an intake checklist.'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='announce',
            field=models.BooleanField(default=True, help_text='Post this to Discord when it is created. Turn off for routine paperwork such as a pasted checklist.'),
        ),
        migrations.AddField(
            model_name='problemreport',
            name='announce',
            field=models.BooleanField(default=True, help_text='Post this to Discord when it is created. Turn off for routine paperwork such as an intake checklist.'),
        ),
    ]
