# Generated by Django 5.2.14 on 2026-06-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='can_write',
            field=models.BooleanField(default=False, help_text='Allow this key to use write endpoints (create reports, change status).'),
        ),
    ]
