# Generated by Django 5.2.12 on 2026-03-15 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_add_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinecomment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_comments_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownercomment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_comments_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownerdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_documents_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
