# Generated by Django 5.2.12 on 2026-03-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_add_related_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalowner',
            name='address',
            field=models.TextField(blank=True, help_text='Physical/mailing address'),
        ),
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.TextField(blank=True, help_text='Physical/mailing address'),
        ),
    ]
