# Generated by Django 5.2.12 on 2026-03-16 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_machinemodel_sort_name'),
        ('catalog', '0020_add_owner_address'),
    ]

    operations = [
    ]
