# Generated by Django 5.2.16 on 2026-07-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_merge_20260316_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zone',
            field=models.CharField(choices=[('front', 'Front of house'), ('workshop', 'Workshop (back of house)'), ('storage', 'Storage (back of house)'), ('hidden', 'Hidden from report')], db_index=True, default='hidden', help_text='Groups machines in the daily maintenance report.', max_length=10),
        ),
    ]
