# Generated by Django 5.2.8 on 2025-11-09 07:36

from django.db import migrations


def create_groups(apps, schema_editor):
    """
    Create default groups with appropriate permissions for the pinball
    problem reporting system.
    """
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get content types for our models
    try:
        game_ct = ContentType.objects.get(app_label='tickets', model='game')
        maintainer_ct = ContentType.objects.get(app_label='tickets', model='maintainer')
        report_ct = ContentType.objects.get(app_label='tickets', model='problemreport')
        update_ct = ContentType.objects.get(app_label='tickets', model='reportupdate')
    except ContentType.DoesNotExist:
        # Content types might not be created yet
        return

    # Create Maintainers group
    maintainers_group, created = Group.objects.get_or_create(name='Maintainers')
    if created or not maintainers_group.permissions.exists():
        maintainer_perms = Permission.objects.filter(
            content_type__in=[report_ct, update_ct, game_ct, maintainer_ct],
            codename__in=[
                # Can manage problem reports
                'add_problemreport',
                'change_problemreport',
                'view_problemreport',
                # Can add updates to reports
                'add_reportupdate',
                'change_reportupdate',
                'view_reportupdate',
                # Can view games (but not modify)
                'view_game',
                # Can view other maintainers
                'view_maintainer',
            ]
        )
        maintainers_group.permissions.set(maintainer_perms)

    # Create Game Managers group
    managers_group, created = Group.objects.get_or_create(name='Game Managers')
    if created or not managers_group.permissions.exists():
        manager_perms = Permission.objects.filter(
            content_type__in=[game_ct, maintainer_ct, report_ct, update_ct],
            codename__in=[
                # Full control over games
                'add_game',
                'change_game',
                'delete_game',
                'view_game',
                # Can manage maintainers
                'add_maintainer',
                'change_maintainer',
                'delete_maintainer',
                'view_maintainer',
                # Can view all reports
                'view_problemreport',
                'view_reportupdate',
            ]
        )
        managers_group.permissions.set(manager_perms)

    # Create Viewers group (read-only access)
    viewers_group, created = Group.objects.get_or_create(name='Viewers')
    if created or not viewers_group.permissions.exists():
        viewer_perms = Permission.objects.filter(
            content_type__in=[game_ct, report_ct, update_ct],
            codename__in=[
                'view_game',
                'view_problemreport',
                'view_reportupdate',
            ]
        )
        viewers_group.permissions.set(viewer_perms)


def remove_groups(apps, schema_editor):
    """
    Remove the groups if migration is reversed.
    """
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Maintainers', 'Game Managers', 'Viewers']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        ('auth', '__latest__'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
