# Generated by Django 5.2.8 on 2025-11-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_machineinstance_ownership_credit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProblemReport',
            new_name='Task',
        ),
    ]
