# Generated by Django 5.2.8 on 2025-11-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_problemreport_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('problem_report', 'Problem Report'),
                    ('task', 'Task'),
                ],
                default='problem_report',
                db_index=True,
                help_text='Problem Report (visitor-reported) or Task (maintainer TODO)',
            ),
        ),
    ]
