# Generated by Django 5.2.8 on 2025-11-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_add_task_type_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportUpdate',
            new_name='LogEntry',
        ),
    ]
