# Generated by Django 5.2.8 on 2025-11-11 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_reportupdate_to_logentry'),
    ]

    operations = [
        # First rename the field
        migrations.RenameField(
            model_name='logentry',
            old_name='report',
            new_name='task',
        ),
        # Then make it nullable
        migrations.AlterField(
            model_name='logentry',
            name='task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='log_entries',
                to='tickets.task',
                null=True,
                blank=True,
            ),
        ),
    ]
