# Generated by Django 5.2.8 on 2025-11-11 06:34

from django.db import migrations, models


def migrate_maintainer_to_maintainers(apps, schema_editor):
    """Migrate existing single maintainer ForeignKey data to ManyToManyField."""
    LogEntry = apps.get_model('tickets', 'LogEntry')

    for log_entry in LogEntry.objects.all():
        if log_entry.maintainer_id:
            log_entry.maintainers.add(log_entry.maintainer_id)


def reverse_migrate_maintainers_to_maintainer(apps, schema_editor):
    """Reverse migration: take first maintainer from m2m and set as FK."""
    LogEntry = apps.get_model('tickets', 'LogEntry')

    for log_entry in LogEntry.objects.all():
        maintainers = log_entry.maintainers.all()
        if maintainers:
            log_entry.maintainer_id = maintainers[0].id
            log_entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_rename_logentry_report_to_task_and_nullable'),
    ]

    operations = [
        # Add the new ManyToManyField
        migrations.AddField(
            model_name='logentry',
            name='maintainers',
            field=models.ManyToManyField(
                to='tickets.maintainer',
                blank=True,
                related_name='log_entries',
            ),
        ),
        # Migrate data from old FK to new M2M
        migrations.RunPython(
            migrate_maintainer_to_maintainers,
            reverse_migrate_maintainers_to_maintainer,
        ),
    ]
