# Generated by Django 5.2.8 on 2025-11-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_add_logentry_maintainers_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='maintainer',
        ),
    ]
