# Generated by Django 5.2.12 on 2026-03-23 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text="Machine-readable identifier (e.g., 'control_power')", max_length=100)),
                ('name', models.CharField(help_text="Human-readable name (e.g., 'Control Machine Power')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Explanation of what this capability allows')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
            options={
                'verbose_name_plural': 'app capabilities',
                'ordering': ['app', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AppCapabilityGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='oauth.appcapability')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['capability__app', 'capability__name', 'user__username'],
            },
        ),
        migrations.AddConstraint(
            model_name='appcapability',
            constraint=models.UniqueConstraint(fields=('app', 'slug'), name='unique_capability_per_app'),
        ),
        migrations.AddConstraint(
            model_name='appcapabilitygrant',
            constraint=models.UniqueConstraint(fields=('user', 'capability'), name='unique_grant_per_user'),
        ),
    ]
